services:
  postgres:
    container_name: urlify-postgres
    image: postgres:18-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
      - APP_DB_NAME=${APP_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - urlify-network

  redis:
    container_name: urlify-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - urlify-network
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 30s
      timeout: 5s
      retries: 5
  
  migration:
    build: 
      context: ./backend
      dockerfile: Dockerfile.migrations
    env_file:
      - ./backend/.env
    networks:
      - urlify-network
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.runtime
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - urlify-network
    depends_on:
      migration:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: ./worker-service
      dockerfile: Dockerfile
    env_file:
      - ./worker-service/.env
    networks:
      - urlify-network
    depends_on:
      migration:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  urlify-network:
    driver: bridge