#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
    -U={$POSTGRES_USER}
    -d={$POSTGRES_DB} << EOF
CREATE ROLE {$APP_DB_USER}
WITH LOGIN
PASSWORD '{$APP_DB_PASSWORD}'
NOSUPERUSER
NOCREATEDB
NOCREATEROLE;
CREATE DATABASE {$APP_DB_NAME} 
OWNER {$APP_DB_USER};
EOF
