import { User, EmailVerificationToken, PasswordResetToken } from '../auth.entity';

export interface IAuthRepository {
  /**
   * Finds a user by their email address.
   *
   * @param email - The email to look up.
   * @returns The matching User entity, or null if not found.
   */
  findByEmail(email: string): Promise<User | null>;

  /**
   * Persists a new user record in the database.
   *
   * @param data - User fields to insert (id is generated by DB).
   * @returns The newly created User entity with all fields populated.
   */
  create(data: Pick<User, 'name' | 'email' | 'passwordHash'>): Promise<User>;

  /**
   * Stores a user's refresh token hash in the database.
   *
   * @param userId - The ID of the user.
   * @param tokenHash - The SHA-256 hash of the refresh token.
   * @param expiresAt - The expiration timestamp.
   */
  storeRefreshToken(userId: string, tokenHash: string, expiresAt: Date): Promise<void>;

  /**
   * Stores a user's email verification token hash in the database.
   *
   * @param userId - The ID of the user.
   * @param tokenHash - The SHA-256 hash of the verification token.
   * @param expiresAt - The expiration timestamp.
   * @returns The created EmailVerificationToken entity.
   */
  createEmailVerificationToken(userId: string, tokenHash: string, expiresAt: Date): Promise<EmailVerificationToken>;

  /**
   * Finds a user by their unique database ID.
   *
   * @param id - The UUID of the user.
   * @returns The matching User entity, or null if not found.
   */
  findById(id: string): Promise<User | null>;

  /**
   * Looks up an email verification token by its hash.
   *
   * @param tokenHash - The SHA-256 token hash.
   * @returns The verification token record, or null if not found.
   */
  findVerificationTokenByHash(tokenHash: string): Promise<EmailVerificationToken | null>;

  /**
   * Updates the status (revocation & expiration) of an email verification token.
   *
   * @param tokenId - The token primary key ID.
   * @param isRevoked - The new revoked status.
   * @param isExpired - The new expired status.
   */
  updateVerificationTokenStatus(tokenId: string, isRevoked: boolean, isExpired: boolean): Promise<void>;

  /**
   * Updates the email verification status flag on a user record.
   *
   * @param userId - The user ID.
   * @param isVerified - The new is_email_verified state.
   */
  updateUserVerificationStatus(userId: string, isVerified: boolean): Promise<void>;

  /**
   * Stores a user's password reset token hash in the database.
   *
   * @param userId - The ID of the user.
   * @param tokenHash - The SHA-256 hash of the password reset token.
   * @param expiresAt - The expiration timestamp.
   * @returns The created PasswordResetToken entity.
   */
  createPasswordResetToken(userId: string, tokenHash: string, expiresAt: Date): Promise<PasswordResetToken>;

  /**
   * Looks up a password reset token by its hash.
   *
   * @param tokenHash - The SHA-256 token hash.
   * @returns The password reset token record, or null if not found.
   */
  findPasswordResetTokenByHash(tokenHash: string): Promise<PasswordResetToken | null>;

  /**
   * Updates a user's password hash in the database.
   *
   * @param userId - The user ID.
   * @param passwordHash - The new password hash.
   */
  updatePassword(userId: string, passwordHash: string): Promise<void>;

  /**
   * Hard deletes a password reset token from the database.
   *
   * @param tokenId - The token primary key ID.
   */
  deletePasswordResetToken(tokenId: string): Promise<void>;
}


