import { User } from '../auth.entity';

export interface IAuthRepository {
  /**
   * Finds a user by their email address.
   *
   * @param email - The email to look up.
   * @returns The matching User entity, or null if not found.
   */
  findByEmail(email: string): Promise<User | null>;

  /**
   * Persists a new user record in the database.
   *
   * @param data - User fields to insert (id is generated by DB).
   * @returns The newly created User entity with all fields populated.
   */
  create(data: Pick<User, 'name' | 'email' | 'passwordHash'>): Promise<User>;

  /**
   * Stores a user's refresh token hash in the database.
   *
   * @param userId - The ID of the user.
   * @param tokenHash - The SHA-256 hash of the refresh token.
   * @param expiresAt - The expiration timestamp.
   */
  storeRefreshToken(userId: string, tokenHash: string, expiresAt: Date): Promise<void>;

  /**
   * Stores a user's email verification token hash in the database.
   *
   * @param userId - The ID of the user.
   * @param tokenHash - The SHA-256 hash of the verification token.
   * @param expiresAt - The expiration timestamp.
   */
  createEmailVerificationToken(userId: string, tokenHash: string, expiresAt: Date): Promise<void>;
}

